name: Release macOS DMG

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-macos:
    runs-on: macos-14
    permissions:
      contents: write
    env:
      PNPM_STORE_PATH: ~/.pnpm-store
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Enable Corepack
        run: corepack enable

      - name: Prepare pnpm
        run: corepack prepare pnpm@9 --activate

      - name: Verify pnpm
        run: pnpm -v

      - name: Cache pnpm store
        uses: actions/cache@v4
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: Install Rust (stable)
        uses: dtolnay/rust-toolchain@stable

      - name: Rust cache
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: |
            src-tauri -> target

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build Tauri app (DMG)
        env:
          CI: true
        run: pnpm tauri build

      - name: Locate DMG
        id: locate
        shell: bash
        run: |
          set -euo pipefail
          DMG_PATH=$(ls -1 src-tauri/target/release/bundle/dmg/*.dmg | head -n 1 || true)
          if [[ -z "$DMG_PATH" ]]; then
            echo "No DMG found in src-tauri/target/release/bundle/dmg" >&2
            exit 1
          fi
          echo "dmg_path=$DMG_PATH" >> "$GITHUB_OUTPUT"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: commander-dmg
          path: ${{ steps.locate.outputs.dmg_path }}

      - name: Create GitHub Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ steps.locate.outputs.dmg_path }}
          generate_release_notes: true
          draft: false
          prerelease: false


